<a href="https://colab.research.google.com/github/Elight-dotcom/data-mining/blob/main/DM_M7_3124600100_Ardanu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M7 - Heart - Data Mining

Nama : Ardanu Egitya Ash Shafah  
NRP : 3124600100  
Kelas : D4 IT D

## Menampilkan dataset heart.csv

### Menambahkan header

In [141]:
import pandas as pd
import numpy as np

data_path = '/content/drive/MyDrive/PENS/Semester 5/Data Mining/heart.csv'

h = [
    "Age",
    "sex",
    "chest pain type",
    "resting blood pressure",
    "serum cholestoral in mg/dl",
    "fasting blood sugar > 120 mg/dl",
    "resting electrocardiographic results",
    "maximum heart rate achieved",
    "exercise induced angina",
    "oldpeak = ST depression induced by exercise relative to rest",
    "the slope of the peak exercise ST segment",
    "number of major vessels (0-3) colored by flourosopy",
    "thal",
    "heart_disease"
]
dataset = pd.read_csv(data_path, header=None, names=h)

dataset

,Age,sex,chest pain type,resting blood pressure,serum cholestoral in mg/dl,fasting blood sugar > 120 mg/dl,resting electrocardiographic results,maximum heart rate achieved,exercise induced angina,oldpeak = ST depression induced by exercise relative to rest,the slope of the peak exercise ST segment,number of major vessels (0-3) colored by flourosopy,thal,heart_disease
0,70,male,asymptomatic,130,322,0,ventricular_hypertrophy,109,no,2.4,flat,3,normal,Presence
1,67,female,non_anginal_pain,115,564,0,ventricular_hypertrophy,160,no,1.6,flat,0,reversable_defect,Absence
2,57,male,atypical_angina,124,261,0,normal,141,no,0.3,upsloping,0,reversable_defect,Presence
3,64,male,asymptomatic,128,263,0,normal,105,yes,0.2,flat,1,reversable_defect,Absence
4,74,female,atypical_angina,120,269,0,ventricular_hypertrophy,121,yes,0.2,upsloping,1,normal,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,male,non_anginal_pain,172,199,1,normal,162,no,0.5,upsloping,0,reversable_defect,Absence
266,44,male,atypical_angina,120,263,0,normal,173,no,0.0,upsloping,0,reversable_defect,Absence
267,56,female,atypical_angina,140,294,0,ventricular_hypertrophy,153,no,1.3,flat,0,normal,Absence
268,57,male,asymptomatic,140,192,0,normal,148,no,0.4,flat,0,fixed_defect,Absence
269,67,male,asymptomatic,160,286,0,ventricular_hypertrophy,108,yes,1.5,flat,3,normal,Presence

In [142]:
# Cek jumlah kategori di kolom katgoerikal
sex_count = dataset['sex'].value_counts()
chest_pain_type_count = dataset['chest pain type'].value_counts()
resting_electrocardiographic_results_count = dataset['resting electrocardiographic results'].value_counts()
exercise_induced_angina_count = dataset['exercise induced angina'].value_counts()
the_slope_of_the_peak_exercise_ST_segment_count = dataset['the slope of the peak exercise ST segment'].value_counts()
thal_count = dataset['thal'].value_counts()

print("Jumlah kategori kolom sex:")
print(sex_count)
print("\nJumlah kategori kolom chest pain type:")
print(chest_pain_type_count)
print("\nJumlah kategori kolom resting electrocardiographic results:")
print(resting_electrocardiographic_results_count)
print("\nJumlah kategori kolom exercise induced angina:")
print(exercise_induced_angina_count)
print("\nJumlah kategori kolom the slope of the peak exercise ST segment:")
print(the_slope_of_the_peak_exercise_ST_segment_count)
print("\nJumlah kategori kolom thal:")
print(thal_count)

Jumlah kategori kolom sex:
sex
male      183
female     87
Name: count, dtype: int64

Jumlah kategori kolom chest pain type:
chest pain type
asymptomatic        129
non_anginal_pain     79
atypical_angina      42
typical_angina       20
Name: count, dtype: int64

Jumlah kategori kolom resting electrocardiographic results:
resting electrocardiographic results
ventricular_hypertrophy    137
normal                     131
wave_abnormality             2
Name: count, dtype: int64

Jumlah kategori kolom exercise induced angina:
exercise induced angina
no     181
yes     89
Name: count, dtype: int64

Jumlah kategori kolom the slope of the peak exercise ST segment:
the slope of the peak exercise ST segment
upsloping      130
flat           122
downsloping     18
Name: count, dtype: int64

Jumlah kategori kolom thal:
thal
normal               152
reversable_defect    104
fixed_defect          14
Name: count, dtype: int64

In [143]:
# Cek missing value
print(dataset.isna().sum())

# Cek duplicate
print("\nData duplikat:", dataset.duplicated().sum())

Age                                                             0
sex                                                             0
chest pain type                                                 0
resting blood pressure                                          0
serum cholestoral in mg/dl                                      0
fasting blood sugar > 120 mg/dl                                 0
resting electrocardiographic results                            0
maximum heart rate achieved                                     0
exercise induced angina                                         0
oldpeak = ST depression induced by exercise relative to rest    0
the slope of the peak exercise ST segment                       0
number of major vessels (0-3) colored by flourosopy             0
thal                                                            0
heart_disease                                                   0
dtype: int64

Data duplikat: 0

### Pemisahan Fitur

In [144]:
features = dataset.copy().drop(columns=['heart_disease'])
target = dataset['heart_disease']

target

0      Presence
1       Absence
2      Presence
3       Absence
4       Absence
         ...
265     Absence
266     Absence
267     Absence
268     Absence
269    Presence
Name: heart_disease, Length: 270, dtype: object

### Encoding

#### Encoding Features

In [145]:
# Encoding biary
features['sex'] = features['sex'].map({'female': 0, 'male': 1})
features['exercise induced angina'] = features['exercise induced angina'].map({'no': 0, 'yes': 1})

# Encoding ordinal
features['the slope of the peak exercise ST segment'] = features['the slope of the peak exercise ST segment'].map({
    'upsloping': 0,
    'flat': 1,
    'downsloping': 2
})

# OHE
nominal_column = ['chest pain type', 'resting electrocardiographic results', 'thal']
features = pd.get_dummies(features, columns=nominal_column, drop_first=True)

features

,Age,sex,resting blood pressure,serum cholestoral in mg/dl,fasting blood sugar > 120 mg/dl,maximum heart rate achieved,exercise induced angina,oldpeak = ST depression induced by exercise relative to rest,the slope of the peak exercise ST segment,number of major vessels (0-3) colored by flourosopy,chest pain type_atypical_angina,chest pain type_non_anginal_pain,chest pain type_typical_angina,resting electrocardiographic results_ventricular_hypertrophy,resting electrocardiographic results_wave_abnormality,thal_normal,thal_reversable_defect
0,70,1,130,322,0,109,0,2.4,1,3,False,False,False,True,False,True,False
1,67,0,115,564,0,160,0,1.6,1,0,False,True,False,True,False,False,True
2,57,1,124,261,0,141,0,0.3,0,0,True,False,False,False,False,False,True
3,64,1,128,263,0,105,1,0.2,1,1,False,False,False,False,False,False,True
4,74,0,120,269,0,121,1,0.2,0,1,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,172,199,1,162,0,0.5,0,0,False,True,False,False,False,False,True
266,44,1,120,263,0,173,0,0.0,0,0,True,False,False,False,False,False,True
267,56,0,140,294,0,153,0,1.3,1,0,True,False,False,True,False,True,False
268,57,1,140,192,0,148,0,0.4,1,0,False,False,False,False,False,False,False
269,67,1,160,286,0,108,1,1.5,1,3,False,False,False,True,False,True,False

#### Encoding Target

In [146]:
target = target.map({'Absence': 0, 'Presence': 1})

target

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: heart_disease, Length: 270, dtype: int64

## Inisialisasi Normalisasi, Klasifikasi Model dan Validation Model

In [147]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, FunctionTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, LeaveOneOut, cross_val_score

# Dictionary Normalisasi
normalization = {
    'Min-Max': MinMaxScaler(),
    'Z-Score': StandardScaler(),
    'Sigmoidal': FunctionTransformer(lambda x: 1 / (1 + np.exp(-x)))
}

# Dictionary Model
models = {
    'k-NN (k=1)': KNeighborsClassifier(n_neighbors=1),
    'k-NN (k=5)': KNeighborsClassifier(n_neighbors=5),
    'k-NN (k=9)': KNeighborsClassifier(n_neighbors=9),
    'Decision Tree': DecisionTreeClassifier(random_state=42)
}

# Dictionary Validasi
cv_methods = {
    'k-Fold (k=4)': StratifiedKFold(n_splits=4, shuffle=True, random_state=42),
    'k-Fold (k=10)': StratifiedKFold(n_splits=10, shuffle=True, random_state=42),
    'LOO': LeaveOneOut()
}

# List kosong untuk hasil
result = []

## Pengerjaan

In [139]:
from sklearn.pipeline import Pipeline

for cv_name, cv in cv_methods.items():
    for scaler_name, scaler in normalization.items():
        for model_name, model in models.items():

            # Gabung scaler dan model dalam satu Pipeline
            pipeline = Pipeline([
                ('scaler', scaler),
                ('model', model)
            ])

            # Jalankan eksperimen dengan cross_val_score
            akurasi_fold = cross_val_score(pipeline, features, target, cv=cv, scoring='accuracy')

            # Hitung rata-rata akurasi dan error ratio
            rata_akurasi = akurasi_fold.mean()
            error_ratio = 1 - rata_akurasi

            # Simpan ke dalam list
            result.append({
                'Validasi': cv_name,
                'Normalisasi': scaler_name,
                'Model': model_name,
                'Error Ratio': error_ratio
            })

In [140]:
# Urutkan berdasarkan error ratio paling kecil
df_result = pd.DataFrame(result)
df_hasil_urut = df_result.sort_values(by='Error Ratio').reset_index(drop=True)

df_hasil_urut

         Validasi Normalisasi          Model  Error Ratio
0   k-Fold (k=10)     Z-Score     k-NN (k=9)     0.162963
1             LOO     Z-Score     k-NN (k=5)     0.166667
2    k-Fold (k=4)     Z-Score     k-NN (k=9)     0.166868
3             LOO   Sigmoidal     k-NN (k=5)     0.170370
4   k-Fold (k=10)     Z-Score     k-NN (k=5)     0.174074
5             LOO     Z-Score     k-NN (k=9)     0.174074
6             LOO   Sigmoidal     k-NN (k=9)     0.174074
7   k-Fold (k=10)   Sigmoidal     k-NN (k=9)     0.174074
8             LOO     Min-Max     k-NN (k=9)     0.177778
9   k-Fold (k=10)     Min-Max     k-NN (k=9)     0.177778
10   k-Fold (k=4)     Z-Score     k-NN (k=5)     0.181738
11  k-Fold (k=10)   Sigmoidal     k-NN (k=5)     0.185185
12   k-Fold (k=4)   Sigmoidal     k-NN (k=5)     0.185360
13   k-Fold (k=4)   Sigmoidal     k-NN (k=9)     0.189201
14   k-Fold (k=4)     Min-Max     k-NN (k=9)     0.189256
15            LOO   Sigmoidal     k-NN (k=1)     0.207407
16  k-Fold (k=10)     Min-Max     k-NN (k=5)     0.211111
17            LOO     Min-Max     k-NN (k=5)     0.211111
18   k-Fold (k=4)   Sigmoidal     k-NN (k=1)     0.215101
19   k-Fold (k=4)     Min-Max     k-NN (k=5)     0.218942
20  k-Fold (k=10)   Sigmoidal     k-NN (k=1)     0.222222
21            LOO   Sigmoidal  Decision Tree     0.240741
22  k-Fold (k=10)   Sigmoidal  Decision Tree     0.244444
23            LOO     Z-Score  Decision Tree     0.244444
24            LOO     Min-Max     k-NN (k=1)     0.244444
25   k-Fold (k=4)   Sigmoidal  Decision Tree     0.244568
26            LOO     Min-Max  Decision Tree     0.248148
27            LOO     Z-Score     k-NN (k=1)     0.262963
28   k-Fold (k=4)     Z-Score     k-NN (k=1)     0.270303
29  k-Fold (k=10)     Min-Max     k-NN (k=1)     0.274074
30  k-Fold (k=10)     Z-Score     k-NN (k=1)     0.277778
31   k-Fold (k=4)     Min-Max  Decision Tree     0.277820
32  k-Fold (k=10)     Z-Score  Decision Tree     0.285185
33  k-Fold (k=10)     Min-Max  Decision Tree     0.285185
34   k-Fold (k=4)     Z-Score  Decision Tree     0.288905
35   k-Fold (k=4)     Min-Max     k-NN (k=1)     0.289179