<a href="https://colab.research.google.com/github/Elight-dotcom/data-mining/blob/main/DM_UTS_3124600100_Ardanu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS - Data Mining

Nama : Ardanu Egitya Ash Shafah  
NRP : 3124600100  
Kelas : D4 IT D

## Menampilkan dataset heart.csv

### Mengambil dataset

In [257]:
import pandas as pd
import numpy as np

data_path = '/content/drive/MyDrive/PENS/Semester 5/Data Mining/titanic.csv'

dataset = pd.read_csv(data_path)
dataset['Sex'] = dataset['Sex'].map({'female': 0, 'male': 1})

dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,Q

In [258]:
data = dataset[['Sex', 'Age', 'Pclass', 'Fare', 'Survived']]
data

     Sex   Age  Pclass     Fare  Survived
0      1  22.0       3   7.2500         0
1      0  38.0       1  71.2833         1
2      0  26.0       3   7.9250         1
3      0  35.0       1  53.1000         1
4      1  35.0       3   8.0500         0
..   ...   ...     ...      ...       ...
886    1  27.0       2  13.0000         0
887    0  19.0       1  30.0000         1
888    0   NaN       3  23.4500         0
889    1  26.0       1  30.0000         1
890    1  32.0       3   7.7500         0

[891 rows x 5 columns]

In [259]:
train_data = dataset.loc[dataset['Age'].notnull(), ['Sex', 'Pclass', 'Fare', 'Survived']]
train_data

     Sex  Pclass     Fare  Survived
0      1       3   7.2500         0
1      0       1  71.2833         1
2      0       3   7.9250         1
3      0       1  53.1000         1
4      1       3   8.0500         0
..   ...     ...      ...       ...
885    0       3  29.1250         0
886    1       2  13.0000         0
887    0       1  30.0000         1
889    1       1  30.0000         1
890    1       3   7.7500         0

[714 rows x 4 columns]

In [260]:
train_label = dataset.loc[dataset['Age'].notnull(), 'Age']
train_label

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: Age, Length: 714, dtype: float64

In [261]:
test_data = dataset.loc[dataset['Age'].isnull(), ['Sex', 'Pclass', 'Fare', 'Survived']]
test_data

     Sex  Pclass     Fare  Survived
5      1       3   8.4583         0
17     1       2  13.0000         1
19     0       3   7.2250         1
26     1       3   7.2250         0
28     0       3   7.8792         1
..   ...     ...      ...       ...
859    1       3   7.2292         0
863    0       3  69.5500         0
868    1       3   9.5000         0
878    1       3   7.8958         0
888    0       3  23.4500         0

[177 rows x 4 columns]

In [262]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_data = pd.DataFrame(scaler.fit_transform(train_data), columns=train_data.columns)

print('Nilai min: \n', train_data.min(axis=0))
print('Nilai max: \n', train_data.max(axis=0))

Nilai min:
 Sex         0.0
Pclass      0.0
Fare        0.0
Survived    0.0
dtype: float64
Nilai max:
 Sex         1.0
Pclass      1.0
Fare        1.0
Survived    1.0
dtype: float64

In [263]:
test_data_scaled = pd.DataFrame(scaler.transform(test_data), columns=test_data.columns)

print(test_data[:10])

    Sex  Pclass      Fare  Survived
5     1       3    8.4583         0
17    1       2   13.0000         1
19    0       3    7.2250         1
26    1       3    7.2250         0
28    0       3    7.8792         1
29    1       3    7.8958         0
31    0       1  146.5208         1
32    0       3    7.7500         1
36    1       3    7.2292         1
42    1       3    7.8958         0

In [264]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(train_data, train_label)

class_result = knn.predict(test_data)
print(class_result)

[35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 34.66666667 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 34.66666667 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 34.66666667 35.33333333 35.33333333
 35.33333333 34.66666667 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 34.66666667 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 34.66666667 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 34.66666667
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 34.66666667 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333 35.33333333
 35.33333333 35.33333333 35.33333333]

In [265]:
data.loc[dataset['Age'].isnull(), 'Age'] = class_result

print("Jumlah data kosong pada kolom Age sekarang:", data['Age'].isnull().sum())

Jumlah data kosong pada kolom Age sekarang: 0

Bagian 2

In [266]:
test_data_path = '/content/drive/MyDrive/PENS/Semester 5/Data Mining/titanic_test.csv'

test_dataset = pd.read_csv(test_data_path)
test_dataset['Sex'] = test_dataset['Sex'].map({'female': 0, 'male': 1})
test_dataset

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",1,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",0,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",1,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",1,NaN,1,1,2668,22.3583,NaN,C

In [267]:
train_data = data[['Sex', 'Age', 'Pclass', 'Fare']]

train_data

     Sex        Age  Pclass     Fare
0      1  22.000000       3   7.2500
1      0  38.000000       1  71.2833
2      0  26.000000       3   7.9250
3      0  35.000000       1  53.1000
4      1  35.000000       3   8.0500
..   ...        ...     ...      ...
886    1  27.000000       2  13.0000
887    0  19.000000       1  30.0000
888    0  35.333333       3  23.4500
889    1  26.000000       1  30.0000
890    1  32.000000       3   7.7500

[891 rows x 4 columns]

In [268]:
train_label = data['Survived']

train_label

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [269]:
test_data = test_dataset[['Sex', 'Age', 'Pclass', 'Fare']].dropna()

print('Jumlah data null', test_data.isnull().sum().sum())

Jumlah data null 0

In [270]:
test_label_path = '/content/drive/MyDrive/PENS/Semester 5/Data Mining/titanic_testlabel.csv'

test_label = pd.read_csv(test_label_path)
test_label = test_label.loc[test_data.index]
test_label = test_label['Survived']

test_label

0      0
1      1
2      0
3      0
4      1
      ..
409    1
411    1
412    1
414    1
415    0
Name: Survived, Length: 331, dtype: int64

In [271]:
train_data = scaler.fit_transform(train_data)

print('Nilai min train_data', train_data.min(axis=0))
print('Nilai max train_data', train_data.max(axis=0))

Nilai min train_data [0. 0. 0. 0.]
Nilai max train_data [1. 1. 1. 1.]

In [272]:
test_data = scaler.transform(test_data)

test_data

array([[1.        , 0.4282483 , 1.        , 0.01528158],
       [0.        , 0.58532295, 1.        , 0.01366309],
       [1.        , 0.77381252, 0.5       , 0.01890874],
       ...,
       [0.        , 0.34656949, 1.        , 0.01517579],
       [0.        , 0.48479517, 0.        , 0.21255864],
       [1.        , 0.47851219, 1.        , 0.01415106]])

In [276]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(train_data, train_label)

class_result = knn.predict(test_data)
print(class_result)

[0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1
 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1
 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1
 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0
 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0
 0 0 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0
 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 1
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0]

In [274]:
total_data = test_label.shape[0]
error = (test_label.values.ravel() != class_result).sum()

print(f"Jumlah Error: {error} dari {total_data} data")

Jumlah Error: 60 dari 331 data

In [275]:
error_ratio = error / total_data

print(f"Error Ratio: {error_ratio * 100:.2f}%")

Error Ratio: 18.13%